import { Market, MarketCategory, MarketStatus, UserStats, Achievement } from '@/types/market';

export const mockMarkets: Market[] = [
  {
    id: '1',
    title: 'Will Bitcoin reach $100,000 by end of 2024?',
    description: 'Bitcoin has been showing strong momentum throughout 2024. With institutional adoption increasing and potential ETF approvals, many analysts are predicting significant price movements.',
    category: MarketCategory.CRYPTO,
    endDate: new Date('2024-12-31'),
    totalVolume: 2500000,
    yesOdds: 68,
    noOdds: 32,
    participants: 15420,
    imageUrl: 'https://images.unsplash.com/photo-1518546305927-5a555bb7020d?w=400&h=300&fit=crop',
    tags: ['bitcoin', 'crypto', 'price-prediction'],
    createdBy: 'crypto_analyst_pro',
    status: MarketStatus.ACTIVE,
    resolutionSource: 'CoinGecko API',
  },
  {
    id: '2',
    title: 'Will the Lakers make the NBA playoffs this season?',
    description: 'The Lakers have had a rocky start to the season but are showing signs of improvement. With key players returning from injury, their playoff chances are being debated.',
    category: MarketCategory.SPORTS,
    endDate: new Date('2024-04-15'),
    totalVolume: 890000,
    yesOdds: 55,
    noOdds: 45,
    participants: 8932,
    imageUrl: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=400&h=300&fit=crop',
    tags: ['nba', 'lakers', 'playoffs'],
    createdBy: 'sports_bettor_123',
    status: MarketStatus.ACTIVE,
    resolutionSource: 'NBA Official Records',
  },
  {
    id: '3',
    title: 'Will Taylor Swift announce a new album in 2024?',
    description: 'Rumors are swirling about Taylor Swift working on new music. Recent social media activity and studio sightings have fans speculating about a surprise announcement.',
    category: MarketCategory.ENTERTAINMENT,
    endDate: new Date('2024-12-31'),
    totalVolume: 445000,
    yesOdds: 72,
    noOdds: 28,
    participants: 12567,
    imageUrl: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&h=300&fit=crop',
    tags: ['taylor-swift', 'music', 'album'],
    createdBy: 'swiftie_predictor',
    status: MarketStatus.ACTIVE,
    resolutionSource: 'Official Artist Channels',
  },
  {
    id: '4',
    title: 'Will OpenAI release GPT-5 before 2025?',
    description: 'With the rapid advancement in AI technology, there\'s speculation about when OpenAI will release their next major model. Industry insiders have been dropping hints.',
    category: MarketCategory.TECHNOLOGY,
    endDate: new Date('2024-12-31'),
    totalVolume: 1800000,
    yesOdds: 42,
    noOdds: 58,
    participants: 9876,
    imageUrl: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=400&h=300&fit=crop',
    tags: ['ai', 'gpt', 'openai'],
    createdBy: 'tech_insider',
    status: MarketStatus.ACTIVE,
    resolutionSource: 'OpenAI Official Announcements',
  },
  {
    id: '5',
    title: 'Will it snow in Miami this winter?',
    description: 'An extremely rare event, but climate patterns have been unusual lately. Some meteorologists are tracking unusual weather systems that could bring unprecedented conditions.',
    category: MarketCategory.WEATHER,
    endDate: new Date('2024-03-20'),
    totalVolume: 50000,
    yesOdds: 5,
    noOdds: 95,
    participants: 2341,
    imageUrl: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=300&fit=crop',
    tags: ['weather', 'miami', 'snow'],
    createdBy: 'weather_watcher',
    status: MarketStatus.ACTIVE,
    resolutionSource: 'National Weather Service',
  },
  {
    id: '6',
    title: 'Will the Federal Reserve cut interest rates in Q1 2024?',
    description: 'Economic indicators are mixed, and the Fed faces pressure from multiple directions. Recent inflation data and employment numbers are key factors.',
    category: MarketCategory.ECONOMY,
    endDate: new Date('2024-03-31'),
    totalVolume: 3200000,
    yesOdds: 78,
    noOdds: 22,
    participants: 18765,
    imageUrl: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=400&h=300&fit=crop',
    tags: ['fed', 'interest-rates', 'economy'],
    createdBy: 'econ_expert',
    status: MarketStatus.ACTIVE,
    resolutionSource: 'Federal Reserve Official Statements',
  },
  {
    id: '7',
    title: 'Will Ethereum transition to proof-of-stake succeed without major issues?',
    description: 'The Ethereum merge to proof-of-stake is one of the biggest events in crypto history. Technical challenges and potential complications are being closely watched.',
    category: MarketCategory.CRYPTO,
    endDate: new Date('2024-06-30'),
    totalVolume: 4100000,
    yesOdds: 85,
    noOdds: 15,
    participants: 22134,
    imageUrl: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=400&h=300&fit=crop',
    tags: ['ethereum', 'pos', 'merge'],
    createdBy: 'eth_developer',
    status: MarketStatus.ACTIVE,
    resolutionSource: 'Ethereum Foundation',
  },
  {
    id: '8',
    title: 'Will there be a major breakthrough in quantum computing in 2024?',
    description: 'Several tech giants are racing to achieve quantum supremacy. Recent developments suggest we might see significant announcements this year.',
    category: MarketCategory.TECHNOLOGY,
    endDate: new Date('2024-12-31'),
    totalVolume: 750000,
    yesOdds: 38,
    noOdds: 62,
    participants: 5432,
    imageUrl: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=400&h=300&fit=crop',
    tags: ['quantum', 'computing', 'breakthrough'],
    createdBy: 'quantum_researcher',
    status: MarketStatus.ACTIVE,
    resolutionSource: 'Peer-reviewed scientific journals',
  },
];

export const mockUserStats: UserStats = {
  totalPredictions: 127,
  correctPredictions: 89,
  accuracy: 70.1,
  totalVolume: 45600,
  currentStreak: 7,
  longestStreak: 15,
  rank: 234,
  reputation: 8543,
};

export const mockAchievements: Achievement[] = [
  {
    id: '1',
    title: 'First Prediction',
    description: 'Made your first prediction',
    iconUrl: '🎯',
    unlockedAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    title: 'Hot Streak',
    description: 'Get 5 predictions correct in a row',
    iconUrl: '🔥',
    unlockedAt: new Date('2024-02-20'),
  },
  {
    id: '3',
    title: 'High Roller',
    description: 'Place a prediction with 100+ SOL stake',
    iconUrl: '💎',
  },
  {
    id: '4',
    title: 'Oracle',
    description: 'Achieve 80% accuracy with 50+ predictions',
    iconUrl: '🔮',
    progress: 89,
    maxProgress: 100,
  },
  {
    id: '5',
    title: 'Community Builder',
    description: 'Create 10 markets that get 100+ participants',
    iconUrl: '🏗️',
    progress: 3,
    maxProgress: 10,
  },
];

// Function to generate more markets on demand
export const generateRandomMarkets = (count: number): Market[] => {
  const titles = [
    'Will AI replace human jobs in customer service by 2025?',
    'Will electric vehicles represent 50% of new car sales by 2026?',
    'Will virtual reality become mainstream for work meetings in 2024?',
    'Will a new social media platform overtake Twitter in users?',
    'Will renewable energy exceed fossil fuels in the US by 2025?',
    'Will humans land on Mars before 2030?',
    'Will cryptocurrency become legal tender in 5+ countries by 2025?',
    'Will the metaverse have 1 billion active users by 2026?',
  ];

  const categories = Object.values(MarketCategory);

  return Array.from({ length: count }, (_, index) => ({
    id: `generated-${Date.now()}-${index}`,
    title: titles[Math.floor(Math.random() * titles.length)],
    description: 'This is a dynamically generated market for demonstration purposes. Real markets would have detailed descriptions and resolution criteria.',
    category: categories[Math.floor(Math.random() * categories.length)],
    endDate: new Date(Date.now() + Math.random() * 365 * 24 * 60 * 60 * 1000), // Random date within next year
    totalVolume: Math.floor(Math.random() * 5000000) + 10000,
    yesOdds: Math.floor(Math.random() * 80) + 10, // 10-90%
    noOdds: 0, // Will be calculated
    participants: Math.floor(Math.random() * 20000) + 100,
    tags: ['auto-generated', 'demo'],
    createdBy: 'market_generator',
    status: MarketStatus.ACTIVE,
    resolutionSource: 'To be determined',
  })).map(market => ({
    ...market,
    noOdds: 100 - market.yesOdds,
  }));
};