[toolchain]
anchor_version = "0.31.1"
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
prediction_markets = "11111111111111111111111111111112"

[programs.devnet]
prediction_markets = "6crfTQztShryQeMRaPG5H5Uf7Zd69wyPRRF4AFBndh9F"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
